{
 "title": "System [bitte]",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=\"cpu-total\",host!~\"ip-.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "mem_used_percent", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Disk used /",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{path=\"/\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Predicted Disk used / in 12 hr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "predict_linear(disk_used_percent{path=\"/\"}[1h], 12 * 3600)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk used Clients /var",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{host=~`^ip-.*$`,path=\"/var\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Predicted Disk used Clients / in 12 hr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "predict_linear(disk_used_percent{host=~`^ip-.*$`,path=\"/var\"}[12h], 12 * 3600)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bandwidth Ingress / Egress",
   "type": "graph",
   "description": "Bandwidth in SI units, bits per second (bps).\nPositive values are ingress, negative are egress.\nBandwidth is time averaged over a 1 minute window.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{interface=\"ens5\"}[1m]) * 8 / 60",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "-rate(net_bytes_sent{interface=\"ens5\"}[1m]) * 8 / 60",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Reads / Writes",
   "type": "graph",
   "description": "Disk activity, time averaged over a 1 minute window.\nPositive values are disk reads, negative are disk writes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_merged_reads{name=\"nvme0n1\"}[1m])",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "-rate(diskio_merged_writes{name=\"nvme0n1\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Misc Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Deadman's Snitch (Constant Alert)",
   "type": "graph",
   "description": "[https://deadmanssnitch.com](https://deadmanssnitch.com)\n* This panel should ALWAYS be in alerting state\n* This enables Deadman's Snitch to report when this monitoring server dies",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "1", "legendFormat": "deadmanssnitch" }
   ]
  },
  {
   "title": "Coredumps",
   "type": "graph",
   "description": "Rate of coredumps per host",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({syslog_identifier=\"systemd-coredump\"}[1h] != \"sshd\" |= \"dumped core\")) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}