{
 "title": "Nomad [bitte]",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_unallocated_disk_value - nomad_client_allocated_disk_value",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "MHz" }
   ],
   "targets": [
    {
     "expr": "nomad_client_unallocated_cpu_value - nomad_client_allocated_cpu_value",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_unallocated_memory_value - nomad_client_allocated_memory_value",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}