{
 "title": "Traefik [Bitte]",
 "description": "Traefik dashboard prometheus",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "traefikHost",
    "label": "traefikHost",
    "query": {
     "query": "label_values(prometheus_traefik_config_reloads_total, host)"
    }
   },
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Return Codes For $service",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_traefik_service_requests_total{host=\"$traefikHost\",service=\"$service\"}",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Average Response Time For $service",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_traefik_service_request_duration_seconds_sum{host=\"$traefikHost\",service=\"$service\"}) / sum(prometheus_traefik_service_requests_total{host=\"$traefikHost\",service=\"$service\"}) * 1000"
    }
   ]
  },
  {
   "title": "Total non-TLS Requests To $service Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_traefik_service_requests_total{host=\"$traefikHost\",service=\"$service\"}[1m]))",
     "legendFormat": "$service"
    }
   ]
  },
  {
   "title": "Total TLS Requests To $service Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_traefik_service_requests_tls_total{host=\"$traefikHost\",service=\"$service\"}[1m])) by (tls_cipher, tls_version)",
     "legendFormat": "{{tls_cipher}} : {{tls_version}}"
    }
   ]
  },
  {
   "title": "Request Duration Heat Map To $service",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_buckets(prometheus_traefik_service_request_duration_seconds_bucket{host=\"$traefikHost\",service=\"$service\"})[1m]))",
     "legendFormat": "$service"
    }
   ]
  },
  {
   "title": "Traefik Configuration Reload Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_traefik_config_reloads_total{host=\"$traefikHost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "prometheus_traefik_config_reloads_failure_total{host=\"$traefikHost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Entrypoint Status Code 200 Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_traefik_entrypoint_requests_total{host=\"$traefikHost\",entrypoint=~\"$entrypoint\",code=\"200\"}[1m])",
     "legendFormat": "{{entrypoint}} : {{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Entrypoint Others Status Code Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_traefik_entrypoint_requests_total{host=\"$traefikHost\",entrypoint=~\"$entrypoint\",code!=\"200\"}[1m])",
     "legendFormat": "{{entrypoint}} : {{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests By Service Per Minute",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_traefik_service_requests_total{host=\"$traefikHost\"}[1m])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests By Entrypoint Per Minute",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_traefik_entrypoint_requests_total{host=\"$traefikHost\",entrypoint =~ \"$entrypoint\"}[1m])) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Service Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_traefik_service_open_connections{host=\"$traefikHost\"}",
     "legendFormat": "{{service}} : {{method}}"
    }
   ]
  },
  {
   "title": "Entrypoint Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_traefik_entrypoint_open_connections{host=\"$traefikHost\"}",
     "legendFormat": "{{entrypoint}} : {{method}}"
    }
   ]
  }
 ]
}