{
 "title": "Vulnix [bitte]",
 "description": "Vulnix reports",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(nomad_namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Everything",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Entries",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (nomad_namespace, nomad_job, nomad_taskgroup, nomad_task, hostname, pname, version, cve) (vulnerability_score[$__range])"
      }
     ]
    }
   ]
  },
  { "title": "Nomad Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Highest Threat per Namespace",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (nomad_namespace) (vulnerability_score{nomad_namespace!=\"\"}[$__range])",
     "legendFormat": "{{nomad_namespace}}"
    }
   ]
  },
  {
   "title": "All Entries",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (nomad_namespace, nomad_job, nomad_taskgroup, nomad_task, pname, version, cve) (vulnerability_score{nomad_namespace!=\"\"}[$__range])"
    }
   ]
  },
  {
   "title": "Threat per Namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "CVSS v3 Base Score" }
   ],
   "targets": [
    {
     "expr": "max by (nomad_namespace) (vulnerability_score{nomad_namespace!=\"\"})",
     "legendFormat": "{{nomad_namespace}} (max)"
    },
    {
     "expr": "avg by (nomad_namespace) (vulnerability_score{nomad_namespace!=\"\"})",
     "legendFormat": "{{nomad_namespace}} (avg)"
    },
    {
     "expr": "min by (nomad_namespace) (vulnerability_score{nomad_namespace!=\"\"})",
     "legendFormat": "{{nomad_namespace}} (min)"
    }
   ]
  },
  {
   "title": "Nomad Jobs ($namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Highest Threat per Job",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (nomad_job) (vulnerability_score{nomad_namespace=\"$namespace\"}[$__range])",
       "legendFormat": "{{nomad_job}}"
      }
     ]
    },
    {
     "title": "All Entries",
     "type": "table",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (nomad_job, nomad_taskgroup, nomad_task, pname, version, cve) (vulnerability_score{nomad_namespace=\"$namespace\"}[$__range])"
      }
     ]
    },
    {
     "title": "Threat per Job",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "CVSS v3 Base Score" }
     ],
     "targets": [
      {
       "expr": "max by (nomad_job) (vulnerability_score{nomad_namespace=\"$namespace\"})",
       "legendFormat": "{{nomad_job}} (max)"
      },
      {
       "expr": "avg by (nomad_job) (vulnerability_score{nomad_namespace=\"$namespace\"})",
       "legendFormat": "{{nomad_job}} (avg)"
      },
      {
       "expr": "min by (nomad_job) (vulnerability_score{nomad_namespace=\"$namespace\"})",
       "legendFormat": "{{nomad_job}} (min)"
      }
     ]
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Highest Threat per Host",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 10, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (hostname) (vulnerability_score{nomad_job=\"\"}[$__range])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "All Entries",
     "type": "table",
     "gridPos": { "h": 11, "w": 14, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (hostname, pname, version, cve) (vulnerability_score{nomad_job=\"\"}[$__range])"
      }
     ]
    },
    {
     "title": "Threat per Host",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "CVSS v3 Base Score" }
     ],
     "targets": [
      {
       "expr": "max by (hostname) (vulnerability_score{nomad_job=\"\"})",
       "legendFormat": "{{hostname}} (max)"
      },
      {
       "expr": "avg by (hostname) (vulnerability_score{nomad_job=\"\"})",
       "legendFormat": "{{hostname}} (avg)"
      },
      {
       "expr": "min by (hostname) (vulnerability_score{nomad_job=\"\"})",
       "legendFormat": "{{hostname}} (min)"
      }
     ]
    }
   ]
  }
 ]
}